version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      go-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      go-major:
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/distro/all"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/distro/core"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"
