project_name: imposter-go

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/imposter-project/imposter-go/internal/version.Version={{.Version}}
    main: ./cmd/imposter
    tags:
      - lambda.norpc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - "build: release"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: imposter-project
    name: imposter-go
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## imposter-go {{ .Tag }} ({{ .Date }})
    
    For installation instructions, please visit https://github.com/imposter-project/imposter-go#installation
    For user documentation, please visit https://docs.imposter.sh
  
  footer: |
    **Full Changelog**: https://github.com/imposter-project/imposter-go/compare/{{ .PreviousTag }}...{{ .Tag }} 