plugin: rest

# System configuration with store data
system:
  stores:
    userData:
      preloadData:
        userId: "123456"
        fullName: "Jane Doe"

resources:
  - path: /user/:id
    method: GET
    log: "User details retrieved for ID: ${context.request.pathParams.id}"
    response:
      statusCode: 200
      content: >
        {
          "id": "${context.request.pathParams.id}",
          "name": "${stores.userData.fullName}",
          "email": "jane.doe@example.com"
        }
      headers:
        Content-Type: application/json
      template: true

  - path: /error
    method: GET
    log: "Error endpoint accessed at ${datetime.now.iso8601_datetime} from ${context.request.headers.User-Agent:-unknown}"
    response:
      statusCode: 400
      content: '{"error": "Bad Request"}'
      headers:
        Content-Type: application/json
