plugin: soap
wsdlFile: service.wsdl

resources:
  - binding: SoapBinding
    operation: getPetByName
    response:
      file: getPetByNameResponse.xml

  - binding: HttpBinding
    operation: getPetByName
    response:
      file: getPetByNameResponse.xml
